# Generated by Django 5.0.1 on 2024-01-18 19:21

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=app.models.default_profile_picture, null=True, upload_to='media'),
        ),
    ]
