# Generated by Django 5.0.1 on 2024-01-21 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_post_upvote_directmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upvote',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postcomment', to='app.comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postlike', to='app.like'),
        ),
    ]
