# Generated by Django 5.0.1 on 2024-01-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
