# Generated by Django 5.0.1 on 2024-01-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_like_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
    ]
