# Generated by Django 5.0.1 on 2024-01-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_like_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
